### ISSUE TITLE
Should not check if authenticated when voting

### ISSUE THREAD

**Issue by yhylord** [HFIProgramming/NoticeBoardwith5.3#20]
In `routes/web.php`:
```php
Route::group(['middleware' => 'auth'], function () {
...

		Route::get('/vote/{id}', 'VoteController@showIndividualVote')->where(['id' => '[0-9]+']);
		Route::post('/vote/{id}', 'VoteController@voteHandler')->where(['id' => '[0-9]+']);
		Route::get('/vote/result/{id}', 'VoteController@showVoteResult')->where(['id' => '[0-9]+']);

...
});
```
However, anonymous users should also be able to vote.

**Comment by yhylord** [comment]
Ok I see the ticket above...Although I'm not sure if putting `ticket` after `id`is the best way...

**Comment by NeverBehave** [comment]
@yhylord That's because `ID` is a **must-have** attribute but ticket isn't. The Laravel Route seems to have trouble when you writing things like `/vote/{id?}/{ticket?}` , If `ID` here is missing, Routes won't work as expectation.
Actually, I do believe we should bind the ticket with particular vote. There is a section of `vote_id` in ticket table.
